name: Integration Tests
on: push

jobs:
  # Label of the container job
  integration-tests-no-ssl-mode:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    container: node:18

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      rabbitmq:
        # Docker Hub image
        image: rabbitmq:3-management
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping && curl -vkI http://localhost:15672/api/auth"
          --health-interval 30s
          --health-timeout 30s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@master
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run the test suite
        run: npm run test:e2e
        env:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
